POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "teste",
    "email": "da123aa@teste.com",
    "birthDate": "20/05/2000",
    "hobbies": [{
        "description": "teste"
    }]
}