GET http://localhost:3003/user?name=ru

###
GET http://localhost:3003/user/fullsearch?name=a

###
GET http://localhost:3003/user/search?sort=type&order=

###
GET http://localhost:3003/user/page?page=2&size=2

###
GET http://localhost:3003/user/oPerations