GET http://localhost:3003/user/all

###
GET http://localhost:3003/user/001

###
GET http://localhost:3003/user?search=a

###
GET http://localhost:3003/task/search?status=done

###
GET http://localhost:3003/task/delayed

###
GET http://localhost:3003/task/002/responsible

###
GET http://localhost:3003/task/003

###
GET http://localhost:3003/task?creatorUserId=001

###
POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Armando",
    "nickname": "armandinho",
    "email": "armando@mandinho.com"
}

###
POST http://localhost:3003/task
Content-Type: application/json

{
    "title": "Cozinhar 1.0",
    "description": "Arroz e feijão",
    "limitDate": "15/07/2020",
    "creatorUserId": "001"
}

###
POST http://localhost:3003/task/responsible
Content-Type: application/json

{
    "task_id": "001",
    "responsible_user_id": "001"
}

###
PUT http://localhost:3003/user/edit/001
Content-Type: application/json

{
    "name": "Astro Dev",
    "nickname": "astrodev"
}

###
PUT http://localhost:3003/task/status/003
Content-Type: application/json

{
    "status": "done"
}

###
DELETE http://localhost:3003/task/001/responsible/010