GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYzc5ZGY1LTkxMjgtNDJkOS1hNzA3LTZmZGJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODcyMzM1NiwiZXhwIjoxNjI4NzI2OTU2fQ.pTuEghH6C5QaTuYrkJBNBaSV4V7UYt1WTS8JtZ3QbPU

###
GET http://localhost:3003/user/967dfc30-1d7d-4356-814c-f2e83fde6cc9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYzc5ZGY1LTkxMjgtNDJkOS1hNzA3LTZmZGJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODcyMzM1NiwiZXhwIjoxNjI4NzI2OTU2fQ.pTuEghH6C5QaTuYrkJBNBaSV4V7UYt1WTS8JtZ3QbPU

###
GET http://localhost:3003/recipe/2,154975
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYzc5ZGY1LTkxMjgtNDJkOS1hNzA3LTZmZGJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODcyMzM1NiwiZXhwIjoxNjI4NzI2OTU2fQ.pTuEghH6C5QaTuYrkJBNBaSV4V7UYt1WTS8JtZ3QbPU

###
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Carla",
    "email": "carla@labenu.com",
    "password": "carla321",
    "role": "aDmiN"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "carla@labenu.com",
    "password": "carla321"
}

###
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYzc5ZGY1LTkxMjgtNDJkOS1hNzA3LTZmZGM1OWMxMmE4ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODcyOTA3MCwiZXhwIjoxNjI4NzMyNjcwfQ.gVqpVQP3rGrvNpZkUeDYEwdMcRcl2oJTQu9fztUADu4

{
    "title": "texto",
    "description": "descrição"
}

###
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYzc5ZGY1LTkxMjgtNDJkOS1hNzA3LTZmZGM1OWMxMmE4ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODc3ODgzMiwiZXhwIjoxNjI4NzgyNDMyfQ.KkgX_0OXVwHNhorlVrHPPucRr-1JCIkDOEDaDINhO3E

{
    "userToFollowId": "1.2654665"
}

###
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYzc5ZGY1LTkxMjgtNDJkOS1hNzA3LTZmZGM1OWMxMmE4ZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTYyODc3ODgzMiwiZXhwIjoxNjI4NzgyNDMyfQ.KkgX_0OXVwHNhorlVrHPPucRr-1JCIkDOEDaDINhO3E

{
    "userToUnfollowId": "1.2654665"
}