POST http://localhost:3003/user
Content-Type: application/json

{
    "email": "email1@email.com",
    "password": "123456"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "email20@email.com",
    "password": "123456"
}